### ISSUE TITLE
Please, sign your releases.

### ISSUE THREAD

**Issue by hugo6390** [az0/bleachbit#100]
Hi, 
I'm bleachbit's Debian Maintainer.

In order to improve the security of bleachbit's releases, I suggest to start signing them. Signing releases allows bleachbit's users to ensure they can trust the code they're downloading.

[Here](https://wiki.debian.org/UpstreamGuide) is some help you might need to do it.

Thanks for your work,
 Hugo

**Comment by az0** [comment]
Hi Hugo,

Since 2009 I sign the sha256sum for all released files and upload it to SourceForge. For example, for BleachBit 1.8 see  bleachbit-1.8-sha256sum.txt.asc under http://sourceforge.net/projects/bleachbit/files/bleachbit/1.8/

My public key is here http://bleachbit.sourceforge.net/bleachbit_public.key

Do you mean something else?

**Comment by hugo6390** [comment]
Oh, my fault... I was only retrieving tarballs on GitHub.
I'll add it to the Debian package, thanks a lot !

**Comment by az0** [comment]
This was too hard to discover, so I added the documentation
http://bleachbit.sourceforge.net/documentation/installation#digital_signatures

And linked the documentation from here
http://bleachbit.sourceforge.net/download/

If anything else needs changed, please let me know.
