### ISSUE TITLE
Supported python versions

### ISSUE THREAD

**Issue by tstenner** [az0/bleachbit#102]
I couldn't find any information on which python versions should be supported.
Currently, the tests are running for 2.6 which isn't supported any more since 2013 while making support for 3.x impossible.
What are the future plans for the supported versions?

**Comment by az0** [comment]
Supported versions are documented here: Python 2.5, 2.6, 2.7.
http://bleachbit.sourceforge.net/documentation/installation

This section got lost in the recent transition to GitHub pages, and I will restore it
https://bleachbit.github.io/docs/

On Windows I use old Python 2.5 and old GTK+ because the it keeps down the size of the installer. I now I need to modernize it, so recently I tested Python 2.7 and GTK 3.14, but a "hello world" installer was a huge 93MB. https://github.com/az0/frozen_pygtk3  

There must be a way to shrink the Windows installer, but it seems non-trivial. Once I can do this, I could quickly move to GTK+3 and Python 2.7 and start to consider Python 3.

Reopen if more info is needed.
