### ISSUE TITLE
Weird Launpad "bug: A bleachbit bug link redirects to Kreetingkard bug

### ISSUE THREAD

**Issue by timofonic** [az0/bleachbit#116]
https://bugs.launchpad.net/bleachbit/+bug/144832

WTF?????

**Comment by az0** [comment]
Where did you find this link?

**Comment by az0** [comment]
I am closing for no response. 

I am guessing the integer at the end was truncated. If you change the integer to another integer within the range, you will notice it skips around projects because the scope of the auto incrementing integer is *all* Launchpad projects (thousands of them) and not just BleachBit. Whenever it finds a valid bug ID, it redirects the URL to the correct project.

If you find where this link was from, maybe it can be fixed.

**Comment by timofonic** [comment]
Sorry, my inattention issues made me forget to reply. It happens me all time, I'm ashamed to publish things because of that but was too curious on this.

I don't remember where I discovered that link, sincerely. I just found it in the url history while looking for the bleachbit URL.

I find amusing Launchpad works that way, I find it incredibly confusing. Maybe my mind is unable to understand why it works that way.
