### ISSUE TITLE
Export list of files to text file

### ISSUE THREAD

**Issue by fduraibi** [az0/bleachbit#126]
I would like to see an export option for the preview list, to export the list of files that need to be deleted.

Advantages:
* I can make a backup of the files before deleting them, so I can recover in case of a problem.
* Delete files that need root permission (from shell script) without having to run the app as root.
* Automating the deletion of the files, so I only need to run the app from time to time to update that list.

Currently I can copy / paste the list of files but i still need to parse it to remove  stuff not related to file names. Also the copy/paste cause the program to crash (see https://github.com/az0/bleachbit/issues/125)

**Comment by az0** [comment]
Thank you for the suggestion, fduraibi

Unless you plan to submit a pull request, please bug file tickets here https://bugs.launchpad.net/bleachbit/

One good for suggestions is here https://www.bleachbit.org/forum/suggestions

**Comment by fduraibi** [comment]
Why not make it centralized! I don't want to have three different accounts to work with this project!

**Comment by az0** [comment]
Yes, I understand the frustration. I use Launchpad for historical reasons and, last I checked, feature parity. I will think about it again and where I would put the issues because BleachBit on GitHub has multiple repositories.

As a workaround for the original issue perhaps consider running BleachBit in the console/in a terminal.
